modelconfig:
  h_dim: 512
  z_dim: 128 #this should be consistent with GAMMAcombo
  n_blocks: 2
  n_recur: -1
  body_repr: ssm2_67_condi_marker
  actfun: lrelu
  is_stochastic: true
  min_logvar: -2.5
  max_logvar: 2.5
  reproj_factor: 0.5

lossconfig:
  ppo_clip_val: 0.2
  reward_discount: 0.99
  gae_decay: 0.97
  kld_thresh: 0.02
  kld_weight: 10.0
  use_facing_reward: true
  use_vposer_reward: true
  use_normalized_movement: true
  use_slow_movement: false
  body_ori_weight: 0.5

trainconfig:
  cfg_1frame_male: MPVAECombo_1frame_male_v10
  cfg_1frame_female: MPVAECombo_1frame_female_v10
  cfg_2frame_male: MPVAECombo_2frame_male_v10
  cfg_2frame_female: MPVAECombo_2frame_female_v10
  goal_disturb_sigma: 10
  goal_thresh: 0.75
  max_depth: 60
  n_gens_1frame: 32
  n_gens_2frame: 1
  num_envs_per_epoch: 8
  batch_size: 1024
  learning_rate_p: 0.0003
  learning_rate_v: 0.0003
  max_train_iter_1f: 3
  max_train_iter_2f: 3
  num_epochs: 500
  saving_per_X_ep: 25
  resume_training: true





